server:
  port: 11003
  servlet:
    encoding:
      charset: UTF-8
spring:
  application:
    name: sca-order-config
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      server-addr: cjtbc.com:8848
      username: nacos
      password: 132132

management:
  endpoints:
    web:
      exposure:
        include: '*'
