server:
  port: 9005
  servlet:
    encoding:
      charset: UTF-8
spring:
  application:
    name: dubbo-order-provider
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#  cloud:
#    nacos:
#      server-addr: cjtbc.com:8848
#      username: nacos
#      password: 132132
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
dubbo:
  application:
    name: dubbo-order-provider
  registry:
    address: nacos://cjtbc.com:8848
    username: nacos
    password: 132132

