server:
  port: 10001
  servlet:
    encoding:
      charset: UTF-8
spring:
  application:
    name: sc-order
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
#  instance:
#    appname: order
  #    hostname: 0.0.0.0
  client:
    #服务注册域地址
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:5001/eureka/
      defaultZone: http://127.0.0.1:5001/eureka/,http://127.0.0.1:5002/eureka/
  instance:
    instance-id: order10001
