server:
  port: 9002
  servlet:
    encoding:
      charset: UTF-8
spring:
  application:
    name: sc-payment
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

eureka:
  #    hostname: 0.0.0.0
  client:
    #服务注册域地址
    service-url:
      #      defaultZone: http://${eureka.instance.hostname}:5001/eureka/
      defaultZone: http://127.0.0.1:5001/eureka/,http://127.0.0.1:5002/eureka/